- op: replace
  path: /data/appsettings_Url
  value: "https://mes.plantsuite.client/"
- op: replace
  path: /data/appsettings_AuthConfig__Issuer
  value: "https://account.plantsuite.client/realms/plantsuite"
