- op: replace
  path: /spec/realm/clients/0/rootUrl
  value: "https://portal.plantsuite.client"
- op: replace
  path: /spec/realm/clients/0/redirectUris/0
  value: "https://alarms.plantsuite.client/*"
- op: replace
  path: /spec/realm/clients/0/redirectUris/1
  value: "https://dashboards.plantsuite.client/*"
- op: replace
  path: /spec/realm/clients/0/redirectUris/2
  value: "https://devices.plantsuite.client/*"
- op: replace
  path: /spec/realm/clients/0/redirectUris/3
  value: "https://entities.plantsuite.client/*"
- op: replace
  path: /spec/realm/clients/0/redirectUris/4
  value: "https://notifications.plantsuite.client/*"
- op: replace
  path: /spec/realm/clients/0/redirectUris/5
  value: "https://portal.plantsuite.client/*"
- op: replace
  path: /spec/realm/clients/0/redirectUris/6
  value: "https://queries.plantsuite.client/*"
- op: replace
  path: /spec/realm/clients/0/redirectUris/7
  value: "https://spc.plantsuite.client/*"
- op: replace
  path: /spec/realm/clients/0/redirectUris/8
  value: "https://tenants.plantsuite.client/*"
- op: replace
  path: /spec/realm/clients/0/redirectUris/9
  value: "https://timeseries.plantsuite.client/*"
