- op: replace
  path: /data/appsettings_Url
  value: "portal.plantsuite.client"
- op: replace
  path: /data/appsettings_AuthConfig__Issuer
  value: "https://account.plantsuite.client/realms/plantsuite"
- op: replace
  path: /data/appsettings_MqttConfig__Hostname
  value: "mqtt.plantsuite.client"
- op: replace
  path: /data/appsettings_ApiUrl__Tenants
  value: "https://tenants.plantsuite.client/api/v1"
- op: replace
  path: /data/appsettings_ApiUrl__Devices
  value: "https://devices.plantsuite.client/api/v1"
- op: replace
  path: /data/appsettings_ApiUrl__Entities
  value: "https://entities.plantsuite.client/api/v1"
- op: replace
  path: /data/appsettings_ApiUrl__Variables
  value: "https://timeseries.plantsuite.client/api/v1"
- op: replace
  path: /data/appsettings_ApiUrl__Dashboards
  value: "https://dashboards.plantsuite.client/api/v1"
- op: replace
  path: /data/appsettings_ApiUrl__Widgets
  value: "https://dashboards.plantsuite.client/api/v1"
- op: replace
  path: /data/appsettings_ApiUrl__Views
  value: "https://queries.plantsuite.client/api/v1"
- op: replace
  path: /data/appsettings_ApiUrl__Queries
  value: "https://queries.plantsuite.client/api/v1"
- op: replace
  path: /data/appsettings_ApiUrl__TimeSeries
  value: "https://timeseries.plantsuite.client/api/v1"
- op: replace
  path: /data/appsettings_ApiUrl__Notifications
  value: "https://notifications.plantsuite.client/api/v1"
- op: replace
  path: /data/appsettings_ApiUrl__Alarms
  value: "https://alarms.plantsuite.client/api/v1"
- op: replace
  path: /data/appsettings_ApiUrl__Spc
  value: "https://spc.plantsuite.client/api/v1"
