- op: replace
  path: /spec/realm/clients/0/rootUrl
  value: "https://portal.mes.client01"
- op: replace
  path: /spec/realm/clients/0/redirectUris/0
  value: "https://alarms.mes.client01/*"
- op: replace
  path: /spec/realm/clients/0/redirectUris/1
  value: "https://dashboards.mes.client01/*"
- op: replace
  path: /spec/realm/clients/0/redirectUris/2
  value: "https://devices.mes.client01/*"
- op: replace
  path: /spec/realm/clients/0/redirectUris/3
  value: "https://entities.mes.client01/*"
- op: replace
  path: /spec/realm/clients/0/redirectUris/4
  value: "https://notifications.mes.client01/*"
- op: replace
  path: /spec/realm/clients/0/redirectUris/5
  value: "https://portal.mes.client01/*"
- op: replace
  path: /spec/realm/clients/0/redirectUris/6
  value: "https://queries.mes.client01/*"
- op: replace
  path: /spec/realm/clients/0/redirectUris/7
  value: "https://spc.mes.client01/*"
- op: replace
  path: /spec/realm/clients/0/redirectUris/8
  value: "https://tenants.mes.client01/*"
- op: replace
  path: /spec/realm/clients/0/redirectUris/9
  value: "https://timeseries.mes.client01/*"
