namespace: plantsuite

resources:
  - ../../../../base/plantsuite/mes

patches:
  - target:
      kind: Deployment
      name: mes
    path: patches/deployment-ops.yaml
  - path: patches/virtualservice-mes.yaml
    target:
      kind: VirtualService
      name: mes
  - path: patches/configmap-appsettings.yaml
    target:
      kind: ConfigMap
      name: mes-appsettings
  - path: patches/secret-env.yaml
    target:
      kind: Secret
      name: plantsuite-mes-env
