- op: replace
  path: /spec/servers/0/hosts/0
  value: "*.mes.client01"
- op: replace
  path: /spec/servers/1/hosts/0
  value: "*.mes.client01"
- op: replace
  path: /spec/servers/2/hosts/0
  value: "mqtt.mes.client01"
- op: replace
  path: /spec/servers/3/hosts/0
  value: "mqtt.mes.client01"
