namespace: plantsuite

resources:
  - ../../../../base/plantsuite/queries

patches:
  - target:
      kind: Deployment
      name: queries
    path: patches/deployment-ops.yaml
  - path: patches/virtualservice-queries.yaml
    target:
      kind: VirtualService
      name: queries
