- op: replace
  path: /data/appsettings-ui.json
  value: |
    {
        "CloudApplication": true,
        "Backend": {
            "Url": "https://workflows.plantsuite.client/elsa/api"
        },
        "JwtToken": {
            "Authority": "https://account.plantsuite.client/realms/plantsuite",
            "ClientId": "ps-iot-portal",
            "ResponseType": "code",
            "DefaultScopes": [
                "openid",
                "profile",
                "email"
            ]
        }
    }
