namespace: plantsuite

resources:
  - ../../../../base/plantsuite/production

patches:
  - target:
      kind: Deployment
      name: production
    path: patches/deployment-ops.yaml
  - path: patches/virtualservice-production.yaml
    target:
      kind: VirtualService
      name: production
