namespace: plantsuite

resources:
  - ../../../../base/plantsuite/workflows

patches:
  - target:
      kind: Deployment
      name: workflows
    path: patches/deployment-ops.yaml
  - path: patches/virtualservice-workflows.yaml
    target:
      kind: VirtualService
      name: workflows
  - path: patches/virtualservice-workflows-ui.yaml
    target:
      kind: VirtualService
      name: workflows-ui
  - path: patches/configmap-appsettings.yaml
    target:
      kind: ConfigMap
      name: workflows-appsettings
