- op: replace
  path: /data/appsettings_Url
  value: "portal.mes.client01"
- op: replace
  path: /data/appsettings_AuthConfig__Issuer
  value: "https://account.mes.client01/realms/plantsuite"
- op: replace
  path: /data/appsettings_MqttConfig__Hostname
  value: "mqtt.mes.client01"
- op: replace
  path: /data/appsettings_ApiUrl__Tenants
  value: "https://tenants.mes.client01/api/v1"
- op: replace
  path: /data/appsettings_ApiUrl__Devices
  value: "https://devices.mes.client01/api/v1"
- op: replace
  path: /data/appsettings_ApiUrl__Entities
  value: "https://entities.mes.client01/api/v1"
- op: replace
  path: /data/appsettings_ApiUrl__Variables
  value: "https://timeseries.mes.client01/api/v1"
- op: replace
  path: /data/appsettings_ApiUrl__Dashboards
  value: "https://dashboards.mes.client01/api/v1"
- op: replace
  path: /data/appsettings_ApiUrl__Widgets
  value: "https://dashboards.mes.client01/api/v1"
- op: replace
  path: /data/appsettings_ApiUrl__Views
  value: "https://queries.mes.client01/api/v1"
- op: replace
  path: /data/appsettings_ApiUrl__Queries
  value: "https://queries.mes.client01/api/v1"
- op: replace
  path: /data/appsettings_ApiUrl__TimeSeries
  value: "https://timeseries.mes.client01/api/v1"
- op: replace
  path: /data/appsettings_ApiUrl__Notifications
  value: "https://notifications.mes.client01/api/v1"
- op: replace
  path: /data/appsettings_ApiUrl__Alarms
  value: "https://alarms.mes.client01/api/v1"
- op: replace
  path: /data/appsettings_ApiUrl__Spc
  value: "https://spc.mes.client01/api/v1"
